---
sudo: required
dist: focal

language: python
python: "2.7"

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Install ansible collection
  - ansible-galaxy collection install git+https://github.com/deltabg/ansible-collection-extended_facts.git,master

script:
  # Basic playbook syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # Trigger
  - ansible-playbook tests/test.yml -i tests/inventory

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
