---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: true

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  #- printf '[defaults]\nroles_path=../' >ansible.cfg
  - ansible-galaxy collection install git+https://github.com/deltabg/ansible-collection-extended_facts.git,master

script:
  # Basic playbook syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # Test
  - ansible-playbook tests/test.yml -i tests/inventory

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
