namespace: deltabg
name: extended_facts
version: 1.0.4
readme: README.md
authors:
- Nedelin Petkov <mlg@abv.bg>
description: Module for extended Ansible facts.
license_file: 'LICENSE'
tags: [ 'automation', 'linux', 'system' ]
dependencies: {}
repository: https://github.com/deltabg/ansible-collection-extended_facts
documentation: https://github.com/deltabg/ansible-collection-extended_facts/tree/master/docs
homepage: https://github.com/deltabg/ansible-collection-extended_facts
issues: https://github.com/deltabg/ansible-collection-extended_facts/issues
build_ignore: 
- tests/
- galaxy.yml
- .git
- '*.pyc'
- '*.retry'
- '*.tar.gz'
